apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-dest-{{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  params:
  - name: url
    value: {{.tag.toRegistry}}
  type: image
