apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: {{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  serviceAccountName: {{.serviceAccountName}}
  timeout: 
  pipelineRef:
    name: {{.collectionID}}-image-retag-pl
  resources:
    - name: docker-src-image
      resourceRef:
        name: docker-src-{{.nameSuffix}}
    - name: docker-dest-image
      resourceRef:
        name: docker-dest-{{.nameSuffix}}
