apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name:  {{.nameSuffix}}
  namespace: {{.namespace}}
spec:
  pipelineRef:
    name: {{.collectionID}}-build-pl
  resources:
  - name: git-source
    resourceRef:
      name: git-{{.nameSuffix}}
  - name: docker-image
    resourceRef:
      name: docker-{{.nameSuffix}}
  serviceAccountName: {{.serviceAccountName}}
  timeout: {{.timeout}}
